max_length: 1000
k_fold: 5

file_path:
  op_path: /home/damaoooo/plc_test/dataset/Dataset_1_asm/opfile.pkl
  root_path: /home/damaoooo/Downloads/Dataset-1/
  save_path: /home/damaoooo/plc_test/dataset/Dataset_1_asm

cache:
  read_op: False
  read_cache: False
  