max_length: 1000
k_fold: 5

file_path:
  op_path: /opt/li_dataset/coreutil_dataset/op_file.pkl
  root_path: /opt/li_dataset/coreutil_dataset
  save_path: /opt/li_dataset/coreutil_dataset

cache:
  read_op: True
  read_cache: False
