max_length: 1000
k_fold: 5

file_path:
  op_path: /home/damaoooo/Project/plc/dataset/openplc/op_file.pkl
  root_path: /home/damaoooo/Project/plc/dataset/openplc
  save_path: /home/damaoooo/Project/plc/dataset/openplc
cache:
  read_op: True
  read_cache: True
