max_length: 1000
k_fold: 5

file_path:
  op_path: /home/damaoooo/Downloads/plc_test/dataset/uboot/op_file.pkl
  root_path: /home/damaoooo/Downloads/plc_test/dataset/uboot
  save_path: /home/damaoooo/Downloads/plc_test/dataset/uboot/test_data

cache:
  read_op: True
  read_cache: True
  