# Hyper-parameter for training
train:
  seed: 1
  max_epochs: 200
  batch_size: 4
  num_workers: 16
  pool_size: 50
  k_fold: 5

hyper_parameters:
  lr: 0.0004
  alpha: 0.2
  dropout: 0.3
  hidden_features: 64
  n_heads: 6
  output_features: 128
  exclusive_arch: null
  exclusive_opt: null

  redis: false

path:
  data_path: dataset/openplc
  data_name: openplc
  # data_path: dataset/openplc
  # load_checkpoint: "lightning_logs/uboot_pearson_5/checkpoints/epoch=26-step=4023.ckpt"
  load_checkpoint: ""
