/home/damaoooo/miniconda3/envs/ml/bin/python main.py --k_fold 5 --max_epoch 10
/home/damaoooo/miniconda3/envs/ml/bin/python main.py --k_fold 5 --max_epoch 20
/home/damaoooo/miniconda3/envs/ml/bin/python main.py --k_fold 5 --max_epoch 30
/home/damaoooo/miniconda3/envs/ml/bin/python main.py --k_fold 5 --max_epoch 40
/home/damaoooo/miniconda3/envs/ml/bin/python main.py --k_fold 5 --max_epoch 50
/home/damaoooo/miniconda3/envs/ml/bin/python main.py --k_fold 5 --max_epoch 60
/home/damaoooo/miniconda3/envs/ml/bin/python main.py --k_fold 5 --max_epoch 70
/home/damaoooo/miniconda3/envs/ml/bin/python main.py --k_fold 5 --max_epoch 80
/home/damaoooo/miniconda3/envs/ml/bin/python main.py --k_fold 5 --max_epoch 90
/home/damaoooo/miniconda3/envs/ml/bin/python main.py --k_fold 5 --max_epoch 100