# Hyper-parameter for training
train:
  seed: 1
  max_epochs: 200
  batch_size: 4
  num_workers: 4
  pool_size: 101
  k_fold: 5

hyper_parameters:
  lr: 0.0004
  alpha: 0.2
  dropout: 0.3
  hidden_features: 64
  n_heads: 6
  output_features: 128
  exclusive_arch: null
  exclusive_opt: null

  redis: false
  mode: file

path:
  # data_path: dataset/coreutil
  data_name: Dataset_1_asm
  data_path: dataset/Dataset_1_asm
  # load_checkpoint: "lightning_logs/version_9/checkpoints/last.ckpt"
  load_checkpoint: ""
